//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 04:48:52 PM CEST 
//


package xyz.adammlynarczyk.exchange;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xyz.adammlynarczyk.exchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xyz.adammlynarczyk.exchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUsdToPlnRequest }
     * 
     */
    public GetUsdToPlnRequest createGetUsdToPlnRequest() {
        return new GetUsdToPlnRequest();
    }

    /**
     * Create an instance of {@link GetEuroToPlnResponse }
     * 
     */
    public GetEuroToPlnResponse createGetEuroToPlnResponse() {
        return new GetEuroToPlnResponse();
    }

    /**
     * Create an instance of {@link GetPlnToEuroResponse }
     * 
     */
    public GetPlnToEuroResponse createGetPlnToEuroResponse() {
        return new GetPlnToEuroResponse();
    }

    /**
     * Create an instance of {@link GetPoundsToPlnRequest }
     * 
     */
    public GetPoundsToPlnRequest createGetPoundsToPlnRequest() {
        return new GetPoundsToPlnRequest();
    }

    /**
     * Create an instance of {@link GetPlnToUsdResponse }
     * 
     */
    public GetPlnToUsdResponse createGetPlnToUsdResponse() {
        return new GetPlnToUsdResponse();
    }

    /**
     * Create an instance of {@link GetEuroToPlnRequest }
     * 
     */
    public GetEuroToPlnRequest createGetEuroToPlnRequest() {
        return new GetEuroToPlnRequest();
    }

    /**
     * Create an instance of {@link GetPlnToPoundsRequest }
     * 
     */
    public GetPlnToPoundsRequest createGetPlnToPoundsRequest() {
        return new GetPlnToPoundsRequest();
    }

    /**
     * Create an instance of {@link GetPlnToPoundsResponse }
     * 
     */
    public GetPlnToPoundsResponse createGetPlnToPoundsResponse() {
        return new GetPlnToPoundsResponse();
    }

    /**
     * Create an instance of {@link GetPlnToUsdRequest }
     * 
     */
    public GetPlnToUsdRequest createGetPlnToUsdRequest() {
        return new GetPlnToUsdRequest();
    }

    /**
     * Create an instance of {@link GetUsdToPlnResponse }
     * 
     */
    public GetUsdToPlnResponse createGetUsdToPlnResponse() {
        return new GetUsdToPlnResponse();
    }

    /**
     * Create an instance of {@link GetPlnToEuroRequest }
     * 
     */
    public GetPlnToEuroRequest createGetPlnToEuroRequest() {
        return new GetPlnToEuroRequest();
    }

    /**
     * Create an instance of {@link GetPoundsToPlnResponse }
     * 
     */
    public GetPoundsToPlnResponse createGetPoundsToPlnResponse() {
        return new GetPoundsToPlnResponse();
    }

}
