//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 04:48:52 PM CEST 
//


package xyz.adammlynarczyk.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xyz.adammlynarczyk.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xyz.adammlynarczyk.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMetersToCentimetersRequest }
     * 
     */
    public GetMetersToCentimetersRequest createGetMetersToCentimetersRequest() {
        return new GetMetersToCentimetersRequest();
    }

    /**
     * Create an instance of {@link GetCentimetersToMetersResponse }
     * 
     */
    public GetCentimetersToMetersResponse createGetCentimetersToMetersResponse() {
        return new GetCentimetersToMetersResponse();
    }

    /**
     * Create an instance of {@link GetMetersToCentimetersResponse }
     * 
     */
    public GetMetersToCentimetersResponse createGetMetersToCentimetersResponse() {
        return new GetMetersToCentimetersResponse();
    }

    /**
     * Create an instance of {@link GetMilesToKilometersResponse }
     * 
     */
    public GetMilesToKilometersResponse createGetMilesToKilometersResponse() {
        return new GetMilesToKilometersResponse();
    }

    /**
     * Create an instance of {@link GetKilometersToMilesRequest }
     * 
     */
    public GetKilometersToMilesRequest createGetKilometersToMilesRequest() {
        return new GetKilometersToMilesRequest();
    }

    /**
     * Create an instance of {@link GetInchesToMetersResponse }
     * 
     */
    public GetInchesToMetersResponse createGetInchesToMetersResponse() {
        return new GetInchesToMetersResponse();
    }

    /**
     * Create an instance of {@link GetMilesToKilometersRequest }
     * 
     */
    public GetMilesToKilometersRequest createGetMilesToKilometersRequest() {
        return new GetMilesToKilometersRequest();
    }

    /**
     * Create an instance of {@link GetMetersToInchesRequest }
     * 
     */
    public GetMetersToInchesRequest createGetMetersToInchesRequest() {
        return new GetMetersToInchesRequest();
    }

    /**
     * Create an instance of {@link GetCentimetersToMetersRequest }
     * 
     */
    public GetCentimetersToMetersRequest createGetCentimetersToMetersRequest() {
        return new GetCentimetersToMetersRequest();
    }

    /**
     * Create an instance of {@link GetInchesToMetersRequest }
     * 
     */
    public GetInchesToMetersRequest createGetInchesToMetersRequest() {
        return new GetInchesToMetersRequest();
    }

    /**
     * Create an instance of {@link GetKilometersToMilesResponse }
     * 
     */
    public GetKilometersToMilesResponse createGetKilometersToMilesResponse() {
        return new GetKilometersToMilesResponse();
    }

    /**
     * Create an instance of {@link GetMetersToInchesResponse }
     * 
     */
    public GetMetersToInchesResponse createGetMetersToInchesResponse() {
        return new GetMetersToInchesResponse();
    }

}
